export const config = {
  CANDY_MACHINE_CONFIG: "FPkxUVGwURRhSmiNRpxpz2hCGKyeimZrxGVpzQ5xQJvS",
  CANDY_MACHINE_ID: "E77FvsKRQY1fRH2XjCfH3v1qbPegzixpSTMJEj1onTn4",
  CANDY_START_DATE: "1639716600",
  TREASURY_ADDRESS: "FrpYA7GuSpAyJkDxNyzwdvbn54LYvfWhmdRn6EQ4iVcR",
};
